import IISKursovaya6ОказаниеКонсультацийEController from '../i-i-s-kursovaya6-оказание-консультаций-e';

var IISKursovaya6ОказаниеКонсультацийENewController = IISKursovaya6ОказаниеКонсультацийEController;
export default IISKursovaya6ОказаниеКонсультацийENewController;
