//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оказание консультаций.
    /// </summary>
    // *** Start programmer edit section *** (ОказаниеКонсультаций CustomAttributes)

    // *** End programmer edit section *** (ОказаниеКонсультаций CustomAttributes)
    [AutoAltered()]
    [Caption("Оказание консультаций")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОказаниеКонсультацийE", new string[] {
            "Дата as \'Дата\'",
            "ВремяКонсультации as \'Время консультации\'",
            "ПредоставленнаяУслуга as \'Предоставленная услуга\'",
            "Клиент.Фамилия",
            "Клиент.Имя",
            "Клиент.Отчество"})]
    [AssociatedDetailViewAttribute("ОказаниеКонсультацийE", "РасчетОставшегосяВремени", "РасчетОставшегосяВремениE", true, "", "Расчет оставшегося времени", true, new string[] {
            ""})]
    [View("ОказаниеКонсультацийL", new string[] {
            "Дата as \'Дата\'",
            "ВремяКонсультации as \'Время консультации\'",
            "ПредоставленнаяУслуга as \'Предоставленная услуга\'",
            "Клиент.Фамилия as \'Фамилия\'"})]
    public class ОказаниеКонсультаций : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fВремяКонсультации;
        
        private IIS.Kursovaya6.Услуга fПредоставленнаяУслуга;
        
        private IIS.Kursovaya6.Клиент fКлиент;
        
        private IIS.Kursovaya6.DetailArrayOfРасчетОставшегосяВремени fРасчетОставшегосяВремени;
        
        // *** Start programmer edit section *** (ОказаниеКонсультаций CustomMembers)

        // *** End programmer edit section *** (ОказаниеКонсультаций CustomMembers)

        
        /// <summary>
        /// ВремяКонсультации.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации CustomAttributes)

        // *** End programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации CustomAttributes)
        public virtual int ВремяКонсультации
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации Get start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации Get start)
                int result = this.fВремяКонсультации;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации Get end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации Set start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации Set start)
                this.fВремяКонсультации = value;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации Set end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.ВремяКонсультации Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеКонсультаций.Дата CustomAttributes)

        // *** End programmer edit section *** (ОказаниеКонсультаций.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.Дата Get start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.Дата Get end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.Дата Set start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.Дата Set end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.Дата Set end)
            }
        }
        
        /// <summary>
        /// ПредоставленнаяУслуга.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга CustomAttributes)

        // *** End programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга CustomAttributes)
        public virtual IIS.Kursovaya6.Услуга ПредоставленнаяУслуга
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга Get start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга Get start)
                IIS.Kursovaya6.Услуга result = this.fПредоставленнаяУслуга;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга Get end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга Set start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга Set start)
                this.fПредоставленнаяУслуга = value;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга Set end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.ПредоставленнаяУслуга Set end)
            }
        }
        
        /// <summary>
        /// Оказание консультаций.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеКонсультаций.Клиент CustomAttributes)

        // *** End programmer edit section *** (ОказаниеКонсультаций.Клиент CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент"})]
        [NotNull()]
        public virtual IIS.Kursovaya6.Клиент Клиент
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.Клиент Get start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.Клиент Get start)
                IIS.Kursovaya6.Клиент result = this.fКлиент;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.Клиент Get end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.Клиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.Клиент Set start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.Клиент Set start)
                this.fКлиент = value;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.Клиент Set end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.Клиент Set end)
            }
        }
        
        /// <summary>
        /// Оказание консультаций.
        /// </summary>
        // *** Start programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени CustomAttributes)

        // *** End programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени CustomAttributes)
        public virtual IIS.Kursovaya6.DetailArrayOfРасчетОставшегосяВремени РасчетОставшегосяВремени
        {
            get
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени Get start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени Get start)
                if ((this.fРасчетОставшегосяВремени == null))
                {
                    this.fРасчетОставшегосяВремени = new IIS.Kursovaya6.DetailArrayOfРасчетОставшегосяВремени(this);
                }
                IIS.Kursovaya6.DetailArrayOfРасчетОставшегосяВремени result = this.fРасчетОставшегосяВремени;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени Get end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени Set start)

                // *** End programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени Set start)
                this.fРасчетОставшегосяВремени = value;
                // *** Start programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени Set end)

                // *** End programmer edit section *** (ОказаниеКонсультаций.РасчетОставшегосяВремени Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОказаниеКонсультацийE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОказаниеКонсультацийE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОказаниеКонсультацийE", typeof(IIS.Kursovaya6.ОказаниеКонсультаций));
                }
            }
            
            /// <summary>
            /// "ОказаниеКонсультацийL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОказаниеКонсультацийL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОказаниеКонсультацийL", typeof(IIS.Kursovaya6.ОказаниеКонсультаций));
                }
            }
        }
    }
}
